version: '3.8'

name: php-converter

services:
  php-converter:
    container_name: php-converter
    user: app
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    volumes:
      - ../.:/var/www/php-converter:cached
    networks:
      - php-converter-network

networks:
  php-converter-network:
    name: php-converter-network
    ipam:
      config:
        - subnet: 172.18.7.0/24
          gateway: 172.18.7.1
